version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: entretien
      MYSQL_USER: dzovi
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234