version: "3.9"

services:
  department:
    build: .
    ports:
      - 3001:3001
    environment:
      MONGO_URL: mongodb+srv://dzoviBackend:dzovic10dhiaovic@clusteryea.495j2ja.mongodb.net/departments?retryWrites=true&w=majority
      PORT: 3001